version: '3'
services:
  mor-talent-assessment:
    container_name: mta_mor-talent-assessment
    restart: on-failure
    build: .
    ports:
      - ${APP_PORT}:${APP_PORT}
    environment:
      APP_PORT: ${APP_PORT}
      DATABASE_URL: ${DOCKER_DATABASE_URL}
      MONGO_URL: ${MONGO_URL}
    depends_on:
      - postgres
      - mongo
    networks:
      - mor-talent-assessment-network

  postgres:
    container_name: mta_postgres
    restart: always
    image: postgres:12-alpine
    ports:
      - '${POSTGRES_PORT}:${POSTGRES_PORT}'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    expose:
      - '${POSTGRES_PORT}'
    command: -p ${POSTGRES_PORT}
    networks:
      - mor-talent-assessment-network

  pgadmin4:
    image: dpage/pgadmin4
    container_name: mta_pgadmin4
    restart: always
    ports:
      - '5050:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    depends_on:
      - postgres
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      - mor-talent-assessment-network

  mongo:
    container_name: mta_mongo
    image: mongo
    restart: always
    ports:
      - '${MONGO_PORT}:${MONGO_PORT}'
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
    command: mongod --port ${MONGO_PORT}
    networks:
      - mor-talent-assessment-network

  mongo-express:
    container_name: mta_mongo-express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongo:${MONGO_PORT}/
    depends_on:
      - mongo
    networks:
      - mor-talent-assessment-network

volumes:
  postgres-data:
  pgadmin-data:
  mongo-data:
networks:
  mor-talent-assessment-network:
    name: mor-talent-assessment-network
    driver: bridge
